name: Main workflow

on:
  push:
    paths-ignore:
      - "**.md"
      - ".all-contributorsrc"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".all-contributorsrc"
  #schedule:
    #- cron: "0 0 * * 5"

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: "emcc --version"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided
